import {
  computeReadingDwellMs,
  countWords,
  type Personality,
  type Point,
  planReadingScan,
  type ReadKind,
  type Rng,
} from '@humanjs/core';
import type { Locator, Page } from 'playwright';
import type { Speed } from '../index';
import { walkMouseAlongPath } from '../internal/mouse-walk';
import { sleep, speedModeFactor } from '../internal/timing';

/** Runtime dependencies for a humanized reading dwell. */
export interface ReadingContext {
  readonly page: Page;
  readonly personality: Personality;
  readonly rng: Rng;
  readonly speed: Speed;
  /**
   * Last known cursor position. Used as the starting point for an eye-scan
   * when `withMotion: true`. Required even when motion is off — the read
   * adapter needs to know where the cursor *would* start if motion is later
   * enabled mid-session.
   */
  readonly getMousePosition: () => Point;
  /** Updates the tracked cursor position after a scan completes. */
  readonly setMousePosition: (point: Point) => void;
}

/**
 * What to read:
 *  - `string`: a Playwright-compatible selector (matches `click()` / `type()`).
 *    The element's `innerText` is resolved and word-counted.
 *  - `Locator`: same, but you already have a Locator handle.
 *  - `{ text }`: literal text (you have the string in hand, no selector).
 *  - `{ words }`: pre-counted (bypass extraction entirely).
 */
export type ReadTarget = string | Locator | { readonly text: string } | { readonly words: number };

export interface ReadOptions {
  /**
   * Reading mode. Built-in multipliers on top of `personality.reading.wpm`:
   *  - `'prose'`: 1.0× (default for non-code targets)
   *  - `'code'`:  0.4× (default when target is a `<pre>` or `<code>` element)
   *  - `'scan'`:  1.8× (skim mode, must be explicit)
   *
   * **Smart defaults:** when `kind` is omitted AND the target is a Locator/
   * selector, the adapter inspects the resolved element's tag — `<pre>` and
   * `<code>` auto-detect as `'code'`; everything else as `'prose'`. An
   * explicit `kind` always wins over auto-detection.
   */
  readonly kind?: ReadKind;
  /** Override the effective WPM multiplier directly. Wins over `kind`. */
  readonly wpmMultiplier?: number;
  /**
   * For selector/Locator targets: scroll the element into the viewport
   * before the dwell. A user can't read what isn't on screen. Defaults to
   * `false` — in most flows the caller has already scrolled there.
   */
  readonly scrollIntoView?: boolean;
  /**
   * For selector/Locator targets: trace a humanized cursor path through the
   * target's bounding box while the dwell elapses, like an eye tracking
   * lines of text. **Defaults to `true`** — "reading" implies looking, and
   * looking implies motion. Pass `false` to skip motion when you only
   * care about the temporal pattern (typical AI-agent use case where
   * the cursor position is irrelevant).
   *
   * The scan path is generated by `planReadingScan` from `@humanjs/core`
   * (same deterministic-by-seed contract as the rest of the library) and
   * walked over the computed dwell duration, so motion finishes exactly as
   * the read does. The cursor's tracked position is updated to the scan's
   * endpoint so the next click starts from where the eye landed.
   *
   * Ignored when the target is `{ text }` or `{ words }` (no bounding box).
   */
  readonly withMotion?: boolean;
}

/** Outcome of a read, returned to the caller for observability. */
export interface ReadResult {
  /** Number of words counted (after whitespace splitting / from caller's `{ words }`). */
  readonly words: number;
  /** Sleep duration in ms. Zero in `speed: 'instant'` or for zero-word inputs. */
  readonly durationMs: number;
  /** Final reading kind used (after auto-detection + explicit-override resolution). */
  readonly kind: ReadKind;
}

/**
 * Executes a humanized reading dwell.
 *
 * Flow:
 *  1. Resolve target → words + (optional) Locator
 *  2. Optionally scroll into view
 *  3. Resolve `kind` (explicit → auto-detected from tag → `'prose'`)
 *  4. Compute dwell via `computeReadingDwellMs` (jittered + scaled)
 *  5. Walk a humanized eye-scan path across the bounding box (default on),
 *    pacing the steps so motion ends exactly as the dwell does
 */
export async function executeRead(
  target: ReadTarget,
  ctx: ReadingContext,
  options: ReadOptions = {},
): Promise<ReadResult> {
  // ── Resolve target → words (+ optional Locator for tag detection / scroll) ─
  let words = 0;
  let locator: Locator | undefined;

  if (typeof target === 'string') {
    locator = ctx.page.locator(target);
  } else if ('words' in target) {
    words = target.words;
  } else if ('text' in target) {
    words = countWords(target.text);
  } else {
    // Only Locator remains in the union after the discriminator checks above.
    locator = target;
  }

  let autoDetectedKind: ReadKind | undefined;

  if (locator) {
    if (options.scrollIntoView) {
      await locator.scrollIntoViewIfNeeded();
    }
    const text = await locator.innerText().catch(() => '');
    words = countWords(text);

    // Auto-detect kind from tag only when caller didn't specify one.
    if (options.kind === undefined) {
      autoDetectedKind = await detectKindFromTag(locator);
    }
  }

  const kind = options.kind ?? autoDetectedKind ?? 'prose';

  const durationMs = computeReadingDwellMs(words, ctx.personality.reading, ctx.rng, {
    kind,
    wpmMultiplier: options.wpmMultiplier,
    personalitySpeed: ctx.personality.speed,
    speedFactor: speedModeFactor(ctx.speed),
  });

  const withMotion = options.withMotion ?? true;
  if (withMotion && locator && durationMs > 0) {
    // Walk a humanized scan path across the rendered text over the dwell
    // duration. `walkMouseAlongPath` paces the steps so motion ends exactly
    // as the read does — no extra sleep needed.
    const box = await locator.boundingBox().catch(() => null);
    if (box) {
      // Per-line rects make sweeps land on actual text edges, not the
      // element's full width — important for `<pre>` / `<code>` blocks
      // where individual lines are far narrower than the container.
      const lineRects = await getLineRects(locator).catch(() => []);
      const path = planReadingScan(box, ctx.rng, {
        start: ctx.getMousePosition(),
        lineRects: lineRects.length > 0 ? lineRects : undefined,
      });
      await walkMouseAlongPath(ctx.page, path, durationMs);
      const final = path[path.length - 1];
      if (final) ctx.setMousePosition(final);
      return { words, durationMs, kind };
    }
    // No box → fall through to a plain sleep (rare but possible if the
    // element disappeared between innerText() and boundingBox()).
  }

  if (durationMs > 0) await sleep(durationMs);

  return { words, durationMs, kind };
}

// ────────── helpers ──────────

/**
 * Returns one rect per visible line of *text* inside the element, in
 * viewport coordinates (same space as `locator.boundingBox()`).
 *
 * Walks text-node descendants and collects each text node's line rects via
 * `Range.getClientRects()`. This is the only way to get tight per-line
 * geometry when the target contains block-level descendants — calling
 * `selectNodeContents` over a `<ul>` or `<div>` would return the block's
 * content box (full container width), not the rendered text edges.
 *
 * Rects on the same visual line (e.g. text broken by `<strong>` / `<em>`)
 * are merged so the planner sweeps each line as a single L→R stroke
 * rather than zigzagging through inline siblings.
 */
async function getLineRects(
  locator: Locator,
): Promise<Array<{ x: number; y: number; width: number; height: number }>> {
  const result = await locator.evaluate((el) => {
    type Rect = { x: number; y: number; width: number; height: number };
    // `4` === `NodeFilter.SHOW_TEXT`. Hardcoded so we don't depend on the
    // global `NodeFilter` being in the Node-side TS lib.
    const walker = el.ownerDocument.createTreeWalker(el, 4);
    const rects: Rect[] = [];
    let node = walker.nextNode();
    while (node) {
      const text = node.textContent ?? '';
      if (text.trim().length > 0) {
        const range = el.ownerDocument.createRange();
        range.selectNodeContents(node);
        for (const r of Array.from(range.getClientRects())) {
          if (r.width > 0 && r.height > 0) {
            rects.push({ x: r.x, y: r.y, width: r.width, height: r.height });
          }
        }
      }
      node = walker.nextNode();
    }

    // Merge rects that sit on the same visual line — text broken by inline
    // siblings ("hello <strong>bold</strong> world") produces three rects
    // with the same y. Merged, that becomes a single L→R stroke across the
    // full line of text.
    rects.sort((a, b) => a.y - b.y || a.x - b.x);
    const merged: Rect[] = [];
    for (const r of rects) {
      const last = merged[merged.length - 1];
      if (last && Math.abs(last.y - r.y) < 1 && r.x - (last.x + last.width) < 6) {
        const right = Math.max(last.x + last.width, r.x + r.width);
        const bottom = Math.max(last.y + last.height, r.y + r.height);
        last.width = right - last.x;
        last.height = bottom - last.y;
      } else {
        merged.push({ ...r });
      }
    }
    return merged;
  });
  // Defensive: validate the evaluate result is an array of rect-shaped
  // objects before handing it to the planner. Cheap, and keeps the planner
  // from ever seeing junk from a mocked evaluate or an exotic test harness.
  if (!Array.isArray(result)) return [];
  return result.filter(
    (r): r is { x: number; y: number; width: number; height: number } =>
      r != null &&
      typeof r === 'object' &&
      typeof (r as { x?: unknown }).x === 'number' &&
      typeof (r as { y?: unknown }).y === 'number' &&
      typeof (r as { width?: unknown }).width === 'number' &&
      typeof (r as { height?: unknown }).height === 'number',
  );
}

/**
 * Inspects the element's tag for the smart default. Only the narrowest
 * heuristic (literal `<pre>` / `<code>` tagName) — CSS class sniffing would
 * be too magical. Returns undefined for anything else, so the caller's
 * resolution chain falls back to `'prose'`.
 */
async function detectKindFromTag(locator: Locator): Promise<ReadKind | undefined> {
  // `evaluate` runs the function in the browser context; Playwright's types
  // give the callback a DOM Element here without needing the lib.dom ref
  // on the Node-side tsconfig.
  const tag = await locator.evaluate((el) => el.tagName?.toLowerCase() ?? '').catch(() => '');
  if (tag === 'pre' || tag === 'code') return 'code';
  return undefined;
}
