/**
 * HumanJS side-by-side comparison — ONE window, ONE set of buttons, TWO
 * cursors converging on the same targets in parallel so you can compare
 * trajectories directly against each other.
 *
 * The cursor paths are generated by the same `bezierPath + humanizePath`
 * math `human.click()` uses internally — we just render the cursors via
 * DOM because Playwright only has one real OS pointer per window.
 *
 * Run with:
 *   pnpm demo:compare
 *
 * Customize the pairing:
 *   PERSONALITY_A=precise PERSONALITY_B=distracted pnpm demo:compare
 */

import {
  bezierPath,
  createRng,
  humanizePath,
  type Personality,
  type Point,
  type PresetName,
  resolvePersonality,
} from '@humanjs/playwright';
import { chromium } from 'playwright';

const WINDOW_WIDTH = 1100;
const WINDOW_HEIGHT = 750;

const ACCENT_A = '#22c55e';
const ACCENT_B = '#f59e0b';

// One shared set of button positions on the canvas.
const BUTTON_POSITIONS: Record<string, Point> = {
  'btn-1': { x: 180, y: 200 },
  'btn-2': { x: WINDOW_WIDTH - 180, y: 200 },
  'btn-3': { x: WINDOW_WIDTH / 2, y: WINDOW_HEIGHT / 2 },
  'btn-4': { x: 180, y: WINDOW_HEIGHT - 180 },
  'btn-5': { x: WINDOW_WIDTH - 180, y: WINDOW_HEIGHT - 180 },
};

const TARGET_SEQUENCE = ['btn-1', 'btn-5', 'btn-2', 'btn-4', 'btn-3'];
const CURSOR_START: Point = { x: 40, y: 80 };

/**
 * Visual slowdown for the demo. The real `human.click()` runs at the
 * personality's native timing — fine in production but too fast to perceive
 * curves and jitter on screen. Slowing the demo preserves the *relative*
 * differences between personalities while making the motion easy to watch.
 *
 * Override with `SLOWDOWN=3 pnpm demo:compare` for an even slower demo.
 */
const DEMO_SLOWDOWN = Number(process.env.SLOWDOWN ?? '2');

/** One animated leg from one point to a target, with its own timing. */
interface PathSegment {
  readonly points: Point[];
  readonly durationMs: number;
  readonly preClickMs: number;
  readonly postActionMs: number;
  readonly target: string;
}

function planSequence(personality: Personality, seed: string): PathSegment[] {
  const rng = createRng(seed);
  const segments: PathSegment[] = [];
  let current = CURSOR_START;
  for (const target of TARGET_SEQUENCE) {
    const end = BUTTON_POSITIONS[target];
    if (!end) continue;
    const raw = bezierPath(current, end, rng, {
      curvature: personality.mouse.curvature,
    });
    const path = humanizePath(raw, rng);
    const durationMs = computeTravelTime(path, personality, rng) * DEMO_SLOWDOWN;
    const preClickMs =
      computeDwellTime(
        personality.dwell.preClickMs,
        personality.dwell.preClickJitter,
        personality,
        rng,
      ) * DEMO_SLOWDOWN;
    const postActionMs =
      computeDwellTime(
        personality.dwell.postActionMs,
        personality.dwell.postActionJitter,
        personality,
        rng,
      ) * DEMO_SLOWDOWN;
    segments.push({ points: path, durationMs, preClickMs, postActionMs, target });
    current = end;
  }
  return segments;
}

/** Mirrors the travel-time math in @humanjs/playwright's mouse module. */
function computeTravelTime(
  path: readonly Point[],
  personality: Personality,
  rng: ReturnType<typeof createRng>,
): number {
  let distance = 0;
  for (let i = 1; i < path.length; i++) {
    const prev = path[i - 1];
    const curr = path[i];
    if (!prev || !curr) continue;
    distance += Math.hypot(curr.x - prev.x, curr.y - prev.y);
  }
  const baseTime = (distance / 1000) * personality.mouse.travelTimeMs;
  const jitterMag = baseTime * personality.mouse.travelTimeJitter;
  const jitter = rng.nextFloat(-jitterMag, jitterMag);
  return Math.max(50, (baseTime + jitter) * personality.speed);
}

/** Mirrors the dwell-time math in @humanjs/playwright's mouse module. */
function computeDwellTime(
  meanMs: number,
  jitter: number,
  personality: Personality,
  rng: ReturnType<typeof createRng>,
): number {
  if (meanMs <= 0) return 0;
  const jitterMag = meanMs * jitter;
  const offset = rng.nextFloat(-jitterMag, jitterMag);
  return Math.max(0, (meanMs + offset) * personality.speed);
}

function buttonStyle(id: string): string {
  const pos = BUTTON_POSITIONS[id];
  if (!pos) return '';
  return `left: ${pos.x}px; top: ${pos.y}px;`;
}

function makeDemoHtml(personalityA: string, personalityB: string): string {
  return /* html */ `
<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>HumanJS — ${personalityA} vs ${personalityB}</title>
    <style>
      :root { color-scheme: dark; }
      * { box-sizing: border-box; }
      body {
        margin: 0;
        height: 100vh;
        background: radial-gradient(circle at 30% 20%, #1a1a2e, #0a0a0a);
        color: #fff;
        font-family: -apple-system, system-ui, sans-serif;
        position: relative;
        overflow: hidden;
      }
      .header {
        position: absolute;
        top: 22px;
        left: 0;
        right: 0;
        text-align: center;
        z-index: 5;
        pointer-events: none;
      }
      .header h1 {
        margin: 0 0 12px;
        font-size: 14px;
        font-weight: 500;
        color: #555;
        letter-spacing: 0.18em;
        text-transform: uppercase;
      }
      .legend {
        display: flex;
        gap: 32px;
        justify-content: center;
        align-items: center;
      }
      .legend-item {
        display: flex;
        align-items: center;
        gap: 10px;
        font-size: 16px;
        font-weight: 500;
      }
      .legend-dot {
        width: 14px;
        height: 14px;
        border-radius: 50%;
        box-shadow: 0 0 12px currentColor;
      }
      .vs {
        font-size: 13px;
        color: #555;
        font-weight: 600;
      }
      .target {
        position: absolute;
        padding: 16px 24px;
        font-size: 14px;
        font-weight: 500;
        font-family: inherit;
        background: linear-gradient(180deg, #334155, #1e293b);
        color: white;
        border: 1px solid #475569;
        border-radius: 10px;
        box-shadow: 0 8px 20px rgba(0, 0, 0, 0.4);
        transition: background 0.3s ease, border-color 0.3s ease, box-shadow 0.3s ease;
        min-width: 130px;
        text-align: center;
        transform: translate(-50%, -50%);
        pointer-events: none;
      }
      /* Ring per cursor that visited this button. */
      .target::before, .target::after {
        content: "";
        position: absolute;
        inset: -4px;
        border-radius: 12px;
        opacity: 0;
        transition: opacity 0.3s ease;
        pointer-events: none;
      }
      .target::before { border: 2px solid ${ACCENT_A}; }
      .target::after  { border: 2px solid ${ACCENT_B}; box-shadow: inset 0 0 0 0 transparent; }
      .target.visited-a::before { opacity: 1; }
      .target.visited-b::after  { opacity: 1; }
      .target.visited-both {
        background: linear-gradient(180deg, #1e293b, #0f172a);
        border-color: #475569;
        box-shadow: 0 8px 32px rgba(34, 197, 94, 0.25), 0 8px 32px rgba(245, 158, 11, 0.25);
      }
      .cursor {
        position: absolute;
        width: 14px;
        height: 14px;
        border-radius: 50%;
        pointer-events: none;
        transform: translate(-50%, -50%);
        z-index: 9999;
      }
      .trail {
        position: absolute;
        width: 5px;
        height: 5px;
        border-radius: 50%;
        pointer-events: none;
        transform: translate(-50%, -50%);
        z-index: 9998;
        animation: fade 2.2s linear forwards;
      }
      @keyframes fade {
        to { opacity: 0; transform: translate(-50%, -50%) scale(0.3); }
      }
      .status {
        position: absolute;
        bottom: 22px;
        left: 0;
        right: 0;
        text-align: center;
        font-family: ui-monospace, SF Mono, monospace;
        font-size: 12px;
        color: #777;
      }
    </style>
  </head>
  <body>
    <div class="header">
      <h1>HumanJS — Same target, different personalities</h1>
      <div class="legend">
        <div class="legend-item">
          <span class="legend-dot" style="background: ${ACCENT_A}; color: ${ACCENT_A};"></span>
          <span style="color: ${ACCENT_A};">${personalityA}</span>
        </div>
        <div class="vs">VS</div>
        <div class="legend-item">
          <span class="legend-dot" style="background: ${ACCENT_B}; color: ${ACCENT_B};"></span>
          <span style="color: ${ACCENT_B};">${personalityB}</span>
        </div>
      </div>
    </div>

    <button class="target" id="btn-1" style="${buttonStyle('btn-1')}">1. Top left</button>
    <button class="target" id="btn-2" style="${buttonStyle('btn-2')}">2. Top right</button>
    <button class="target" id="btn-3" style="${buttonStyle('btn-3')}">3. Center</button>
    <button class="target" id="btn-4" style="${buttonStyle('btn-4')}">4. Bottom left</button>
    <button class="target" id="btn-5" style="${buttonStyle('btn-5')}">5. Bottom right</button>

    <div class="cursor" id="cursor-a" style="background: ${ACCENT_A}; box-shadow: 0 0 14px ${ACCENT_A}aa;"></div>
    <div class="cursor" id="cursor-b" style="background: ${ACCENT_B}; box-shadow: 0 0 14px ${ACCENT_B}aa;"></div>

    <div class="status" id="status">Press play…</div>

    <script>
      function animateCursor(opts) {
        const { cursorId, segments, accent, visitedMarker } = opts;
        const cursor = document.getElementById(cursorId);
        let index = 0;

        function trailDot(x, y) {
          const dot = document.createElement('div');
          dot.className = 'trail';
          dot.style.left = x + 'px';
          dot.style.top = y + 'px';
          dot.style.background = accent;
          document.body.appendChild(dot);
          setTimeout(() => dot.remove(), 2200);
        }

        function play() {
          if (index >= segments.length) {
            opts.onDone();
            return;
          }
          const seg = segments[index];
          const startTime = performance.now();

          function frame() {
            const elapsed = performance.now() - startTime;
            const progress = Math.min(1, elapsed / seg.durationMs);
            const exact = progress * (seg.points.length - 1);
            const i = Math.floor(exact);
            const t = exact - i;
            const a = seg.points[i];
            const b = seg.points[Math.min(i + 1, seg.points.length - 1)];
            const x = a.x + (b.x - a.x) * t;
            const y = a.y + (b.y - a.y) * t;
            cursor.style.left = x + 'px';
            cursor.style.top = y + 'px';
            if (i % 2 === 0) trailDot(x, y);
            if (progress < 1) {
              requestAnimationFrame(frame);
            } else {
              // Pre-click hover dwell: the cursor settles on the target.
              setTimeout(() => {
                const btn = document.getElementById(seg.target);
                btn.classList.add(visitedMarker);
                if (btn.classList.contains('visited-a') && btn.classList.contains('visited-b')) {
                  btn.classList.add('visited-both');
                }
                // Post-action dwell: the cursor lingers after the click before
                // starting the next motion. The +250 floor keeps a minimum
                // perceptible gap between clicks even for fast personalities.
                index++;
                setTimeout(play, seg.postActionMs + 250);
              }, seg.preClickMs);
            }
          }
          requestAnimationFrame(frame);
        }
        play();
      }

      window.__startDemo = (data) => {
        const status = document.getElementById('status');
        let doneCount = 0;
        const onDone = () => {
          doneCount++;
          if (doneCount === 2) status.textContent = '✓ Both lanes complete';
        };
        status.textContent = 'Running ' + data.left.length + ' clicks per lane…';
        animateCursor({
          cursorId: 'cursor-a',
          segments: data.left,
          accent: '${ACCENT_A}',
          visitedMarker: 'visited-a',
          onDone,
        });
        animateCursor({
          cursorId: 'cursor-b',
          segments: data.right,
          accent: '${ACCENT_B}',
          visitedMarker: 'visited-b',
          onDone,
        });
      };
    </script>
  </body>
</html>
`;
}

async function main() {
  const personalityA = (process.env.PERSONALITY_A ?? 'careful') as PresetName;
  const personalityB = (process.env.PERSONALITY_B ?? 'distracted') as PresetName;

  console.log(`Same buttons, two cursors: ${personalityA} vs ${personalityB}`);
  console.log(`Demo slowdown: ${DEMO_SLOWDOWN}× (override with SLOWDOWN=… env var)`);
  console.log(`Same Bezier+humanize math as human.click(), rendered in one window.\n`);

  const resolvedA = resolvePersonality(personalityA);
  const resolvedB = resolvePersonality(personalityB);
  const segmentsA = planSequence(resolvedA, personalityA);
  const segmentsB = planSequence(resolvedB, personalityB);

  const browser = await chromium.launch({
    headless: false,
    args: [`--window-size=${WINDOW_WIDTH},${WINDOW_HEIGHT}`],
  });
  const context = await browser.newContext({
    viewport: { width: WINDOW_WIDTH, height: WINDOW_HEIGHT },
  });
  const page = await context.newPage();
  await page.setContent(makeDemoHtml(personalityA, personalityB));

  await new Promise((resolve) => setTimeout(resolve, 1200));

  await page.evaluate(
    ({ left, right }) => {
      // biome-ignore lint/suspicious/noExplicitAny: window extension for the demo
      (window as any).__startDemo({ left, right });
    },
    { left: segmentsA, right: segmentsB },
  );

  const totalDurationA = segmentsA.reduce(
    (sum, s) => sum + s.durationMs + s.preClickMs + s.postActionMs + 250,
    0,
  );
  const totalDurationB = segmentsB.reduce(
    (sum, s) => sum + s.durationMs + s.preClickMs + s.postActionMs + 250,
    0,
  );
  const maxDuration = Math.max(totalDurationA, totalDurationB);
  console.log(`Estimated runtime: ${Math.round(maxDuration / 1000)}s\n`);

  await new Promise((resolve) => setTimeout(resolve, maxDuration + 5000));
  await browser.close();
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
